### ISSUE TITLE
Error al crear la BD

### ISSUE THREAD

**Issue by Xaruca** [jmueller17/Aixada#130]
He intentat crear la nova versió i em dona un error al exportar el fitxer sql/setup/aixada_insert_defaults.sql  en el mysql

Aquest es l'error que dona:
--------------------------------------------------------
INSERT INTO aixada_incident_type
VALUES ( 1,  'internal',  'incidents are restricted to loggon in users.' ) , ( 2,  'internal + email', 'like 1 + incidents are send out as email if possible' ) , ( 3,  'internal + portal',  'like 1 + incidents are posted on the portal' ) , ( 4, 'internal + email + portal',  'Incidents are posted internally, send out as email and posted on the portal' ) ;

MySQL diu: Documentació

#1146 - Table 'aixada.aixada_incident_type' doesn't exist 
---------------------------------------------------------
Es com si en el primer pas de importar el sql/aixada.sql  li faltes alguna taula per importar, concretament la taula aixada_incident_type

Seguim

**Comment by jorix** [comment]
Prova d'execitar el `/sql/dbUpgradeTo2.8.sql`

**Comment by jorix** [comment]
Disculpa abans he fet una lectura ràpida, he pensat que era un altra taula. 

Has de crear la taula tal qual està definida a `sql/aixada.sql`, i pensar que ha pasat que has fet abans per perdre una taula.

**Comment by jmueller17** [comment]
Hola, 
no el problema era que en parte la modularización no estaba acabado para los incidencias y quedaban restos de la vieja install procedures. con el último commit debería funcionar.
