### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by fcojgodoy** [jmueller17/Aixada#133]
All installed according to instructions. In free hosting in Hostinger. But in login with 'admin' 'admin' i get: "CALL retrieve_credentials('admin','0') generated error 1267: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='"
You can try in http://aixadademo.esy.es/

**Comment by jorix** [comment]
It happens, you must be sure that the collate of the schema is `utf8_general_ci`.

To correct your problem now:
   * Change collate of the your *Aixada* echema using phpMyAdmin (option *Collation* on tab *Operations*) or executing:
```sql
     ALTER SCHEMA `my_aixada_db_name`  DEFAULT COLLATE utf8_general_ci ;
```

   * and then, run `sql/setup/aixada_queries_all.sql` **again**.

**Comment by fcojgodoy** [comment]
Thank! It's work.

**Comment by jorix** [comment]
Ok, Wiky updated!
