### ISSUE TITLE
Config logo image

### ISSUE THREAD

**Issue by davidromani** [jmueller17/Aixada#141]
Add config attribute to easly change main logo image.

**Comment by jorix** [comment]
@davidromani: see commit: 196cf437ab26196950249b77516f08277dc8c937  on branch [a-custom](https://github.com/jorix/Aixada/tree/a-custom).
What do you think about this proposal?

**Comment by jorix** [comment]
See #145

**Comment by jorix** [comment]
Now #145 is merged on `master` branch.
