### ISSUE TITLE
Config revolutionary tax

### ISSUE THREAD

**Issue by davidromani** [jmueller17/Aixada#149]
It is possible to change revolutionary tax amounts?

**Comment by jorix** [comment]
AFAIK, currently only via SQL.

Opps!, and `manage_table.php?table=aixada_rev_tax_type` fails.

**Comment by jmueller17** [comment]
This is the table manager which relies upon automatically generated queries. Not sure where it runs havoc though since it works with other tables. Fastest surely to insert a new rev_tax_type via phpmyadmin directly into the table "aixada_rev_tax_type"

**Comment by jorix** [comment]
I have done 75% of the work for a version of table_manager not using automatically generated code (automatically generated code [`canned_responses_XX.php`+`sql/queries/canned_queries.sql`] Is used to write a php with sql+js associated with each table, and each table in a file)

**Comment by jmueller17** [comment]
This is also resolved in dev3 with a new architecture.

**Comment by jorix** [comment]
See PR #153

**Comment by jmueller17** [comment]
Merged into master.
