### ISSUE TITLE
UF don´t show

### ISSUE THREAD

**Issue by acacioperez** [jmueller17/Aixada#151]
In a new instalation of l'aixada 2.8, in the menu "gestionar -> UF y miembros", the UF's that i have created don't show. in internet explorer, show me a error "Error: Invalid XML ..."
The same error ocurrs in the menu "Micuenta -> configuracion"
could you help me?
Thanks
Cuando intentover las UF que he creado aparece un error de InvalidXML. Lo mismo ocurre en el menu "Mi Cuenta -> configuración"
¿Podeis ayudarnos?
Gracias

**Comment by jorix** [comment]
Aplica el cambio del PR #134

Llevamos tiempo con este problema que hace pinta de un bug de PHP. 

NOTA: Por otro lado hace poco se han aplicado algunos cambios en `master`, supongo que cuando hablas de 2.8 quieres decir `master`

**Comment by jmueller17** [comment]
Funciona ahora con el último merge?

**Comment by acacioperez** [comment]
Perdona por no contestarte

Si funciono

He intentado cerrar el bug que puse, pero no lo encontre

Mil gracias por todo vuestro trabajo

Un Saludo
Acacio

Date: Thu, 11 Jun 2015 13:06:59 -0700
