### ISSUE TITLE
witch is the best way to update

### ISSUE THREAD

**Issue by javigomez** [jmueller17/Aixada#156]
Hi, we installed last week a copy of Aixada forked from "master" branch.

I think a bug was preventing us the normal use. I saw a few commits this week. I wondered if updating to latest will solve that bugs. but the question is "how" to update?

If I already have Aixada running on a server, witch is the best way to update to latests in "master"? is just about updating the files via git pull, or do I need to do any special change in the database?

I wonder specially what to do witch changes like this one: https://github.com/jmueller17/Aixada/commit/34afa193e6fcb3ce73758ea496781f62bd652668

Thanks very much

I'm happy to contribute to the wiki with the update instructions once I figure out the "how to"

**Comment by jmueller17** [comment]
The queries are usually easy to update, they simply overwrite the existing stored procedures with the new ones and that's it. Best way: while in sql/ directory, connect to database client, choose database and then 
'source setup/aixada_setup_queries.sql' which will source all individual sql query files. 

The problems is rather the most recent commit regarding the changes to the database itself.  Right now everything is in upgradeTo2.8.sql even though you might have installed the latest branch and most changes in this file do not apply minus the last two statements. We have to provide a separate update file for this. What do you think @jorix ?

**Comment by jorix** [comment]
Paso al castellano que me es más fácil.

Se debe actualizar la base de datos, la pregunta que debéis haceros es **¿cual el punto de partida de la base de datos que usáis?**. 
**Ver comentario en en #154** donde comento los puntos de partida de la migración de datos.
Se trata de ejecutar **solo** los pasos de `upgradeTo2.8.sq` que requiere tu base de datos.

Luego se debe refrescar preventivamente **todos los procedimientos almacenados** en la base de datos ejecutando todos los sql que hay en `sql/queries` o como método alternativo ejecutar el `sql/setup/aixada_queries_all.sql`

@jmueller17: ¿Deberiamos haber cerrado antes la versión 2.8? Aún tenemos trabajo pendiente por ejemplo documentando CANGELOG. 
También deberíamos indicar en la instalación que después de QUALQUIER actualización de código php conviene actualizar otra vez preventivamente TODOS los procedimientos almacenados.

@javigomez Te todas maneras ve comentando qué pasos vais dando y qué os sigue fallando y os vamos ayudando.

**Comment by jmueller17** [comment]
Sí, de momento el uso de las versiones no es muy consistente. Hay en la base de datos la table con la version pero de la 2.8 no se mueve. 
@jorix Nosotros ya no estamos añadiendo cosas a la 2.8. Si lo damos por cerrado lo tienes que decir más bien tu.

**Comment by jorix** [comment]
@jmueller17 see at PR #158

**Comment by jorix** [comment]
> Nosotros ya no estamos añadiendo cosas a la 2.8. Si lo damos por cerrado lo tienes que decir más bien tu. 

Sí sí ya se... a mi me gustaría añadir y unos detallitos:
 * Mejorar la interficie de reabrir pedido (ser más explicito en el vinculo)
 * Mejorar el volver a revisar un pedido ya distribuido pero pendiente de validar: no es necesario borrar la revisión y en cambio se debe limpiar los posible carros que queden vacíos.
 * revisión del js: comas sobrantes y uso de variable no declaradas (lo tengo casi hecho), uso el closure compiler.
 * Permitir añadir una UF en la revisión de pedido (La UF--con el nombre de la coop-- que se queda lo que nadie a recogido) es una idea de Travalera que en ciertos caso a nosotros también nos serviría.
 * Y nosotros usamos una copia de BD desde Aixada que no requiere scripts, o sea funciona en cualquier host! Opción Configurable

**Comment by javigomez** [comment]
He conseguido actualizar pero sigo con el problema: se crean nuevas UF y nuevos proveedores pero no aparecen en  la lista. He grabado este video con el problema:

https://www.youtube.com/watch?v=2hGdEh6caMw

**Comment by javigomez** [comment]
Al rato me han aparecido!!! sin embargo ahora no me deja borrar:

http://www.youtube.com/watch?v=WUYVQn1V3Hg

Puede ser que haya  algún tipo de caché en la aplicación?

**Comment by javigomez** [comment]
mmm que raro, en local parece que sí funciona. Igual es algún tipo de caché de mi hosting. sigo investigando...

**Comment by javigomez** [comment]
Igual es algo de mi configuración. Si lo hago en mi localhost, funciona y veo esto:

![screen shot 2015-07-12 at 21 06 07](https://cloud.githubusercontent.com/assets/1375475/8639396/f4f86920-28d8-11e5-8a8b-8b2799ccc5bd.png)

En cambio si lo hago en el servidor veo esto:

![screen shot 2015-07-12 at 21 05 16](https://cloud.githubusercontent.com/assets/1375475/8639397/0036c44e-28d9-11e5-91f6-47e622894040.png)

**Comment by javigomez** [comment]
He abierto un ticket en la empresa de hosting. Quizá tenga que ver con su configuración de nginx o algo así. Podría ser?

**Comment by jorix** [comment]
Me he encontrado con algunas dificultades con Aixada en diversos hostings, pero esta es nueva. 

Como dices tu parece tema de cache, para salir de dudas prueba este cambio b61713d8f9ad16245944b2ce33bda78a2933c77c en `manage_providers.php`. 

Y por favor dinos si funciona con tu hosting nginx.

**Comment by javigomez** [comment]
funciona!!!

Pues habrá que añadir esa línea en el resto de listados, porque en manage_ufmember.php tambien pasa.

**Comment by jorix** [comment]
BIEN! 

> Pues habrá que añadir esa línea en el resto de listados

Si claro, mañana por la tarde tengo tiempo de preparar un PR con esto. ...y pronto estará en master

**Comment by jorix** [comment]
@javigomez : Ya he preparado esto en el PR #185 

NOTA: **Es necesario que vuelvas a ejecutar el** `sql/setup/aixada_queries_all.sql`**!!!**
Si quieres usarlo ya coge mi rama [Aixada-master](https://github.com/jorix/Aixada/tree/Aixada-master) ahí está todo y el *sql* es correcto, en cambio en *master* al *sql* aún le falta aplicar el #173

**Comment by jmueller17** [comment]
ya está...

**Comment by javigomez** [comment]
Gracias!!!

Lo estoy probando y de momento parece que todo funciona bien. Si encuentro algo aviso

Gracias de nuevo
