### ISSUE TITLE
Cómo borrar UFs?

### ISSUE THREAD

**Issue by javigomez** [jmueller17/Aixada#187]
es posible borrar UFs?

![screen shot 2015-07-14 at 18 11 09](https://cloud.githubusercontent.com/assets/1375475/8678070/caa9bce8-2a52-11e5-9149-dc8f4ea610df.png)

Tengo varios creados para hacer los tests y quisiera borrarlos pero no veo opción.

**Comment by jorix** [comment]
> es posible borrar UFs?

Pues yo no conozco la manera (siempre queda el SQL o renombrarlas) Ten en cuenta que si has hecho compras, pedidos o depósitos deberás también borrarlos.

**Comment by javigomez** [comment]
Ok. Entonces cierro el issue.
