### ISSUE TITLE
Barcode interface usability tweaks

### ISSUE THREAD

**Issue by thewaywest** [jmueller17/Aixada#199]
Using aixada.mespilus.org -- might be a branch (?). at any rate, the barcode scanner works great, but could use a few minor touches to improve usability:
- when gun scans correctly, and the barcode is filled in, focus should be set to the quantity field
- when quantity typed in, focus should be set back to the barcode field and the contents cleared for the next item

attached is initial part of Stock | Barcodes taken from my home screen -- barcode feature not avail without the gun I think.

![stock - barcodes - screencap](https://cloud.githubusercontent.com/assets/14016919/14335141/583761a4-fc59-11e5-81c5-e5471e287a9d.jpg)

**Comment by jorix** [comment]
This is not `master` branch :-(

(see [shop_and_order.php#L486](https://github.com/jmueller17/Aixada/blob/master/shop_and_order.php#L486) ) 

NOTE: Last year `master` branch is updated/fix on various topics/bugs that might be of interest ([CANGELOG-es](https://github.com/jmueller17/Aixada/blob/master/CHANGELOG-es.md))

**Comment by thewaywest** [comment]
Oops. Thanks for your reply, just finding it now. 

I wonder where that Barcode block came from... :( Know how I might track it down?

**Comment by jorix** [comment]
@thewaywest : Estaría bien luego integrar la bifurcación de código de barra en `master` vía PR

**Comment by thewaywest** [comment]
De acuerdo -- recién llegué al proyecto, y solo ayer entendí que nuestro código para usar código de barras para "estoc" fue creado "in-house". He creado un fork ayer, y voy a intentar incorporar los cambios tan rápido cuanto posible, ofreciendo-los para inclusión en el master.
