### ISSUE TITLE
axiada + ubuntu 16.04 + php 7.0 -- roles/users errors

### ISSUE THREAD

**Issue by thewaywest** [jmueller17/Aixada#207]
When migrating to a new server, we created an exact copy of our instance of Aixada. Source Ubutnu 14.04 + Nginx + PHP 5.x, target Ubuntu 14.04 + Nginx + PHP 7.x. We copied the /var/www/aixada directory and database verabtim.

It spins up and _mostly_ runs fine. Problems, however, exist:
- regular users can see and enter administrative section of the app (facturas, for example)
- managing roles spins and fails, no error message
- user report appears but with an error dialog:
  `An error "Internal Server Error", status "error" occurred during loading data:`
  There is no further text with this message.

I have checked every log I could find, including the aixada logs (empty) and system logs (nothing relevant).

Any thoughts or direction for further tests would be appreciated! We are on line, but insecure.

**Comment by jorix** [comment]
Oops! AFAIK for now Aixada 1.x is not tested on PHP 7.x  
(the work is pending...)

**Comment by thewaywest** [comment]
Oops. An oversight, and we're already in production. It might be easier 
for us to fix PHP 7 issues than to rebuild from scratch. Is there any 
way we can help the process along? Not sure how to debug...

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jorix** [comment]
Miraré a ver qué puedo hacer...

Cuando esté en casa montaré un Php 7 para reproducir los errores en
desarrollo y cuando tenga algo voy informando.

**Comment by thewaywest** [comment]
Gracias, Xavi. No stress: tenemos demandes mañana, entonces decimos subir una máquina virtual nueva c Trusty. 

Se encuentras algo fácil, estoy trabajando hoy para tener algo funcionando -- lo más rápido preferido :)

Mark

**Comment by jorix** [comment]
@thewaywest : Localizado!

La herramienta utilizada por Aixada para generar PDF tiene diversos puntos de incompatibilidad con PHP-7.

Desactivar la herramienta **mPdf** para salir del apuro: 
 * En `php/ctrl/SmallQ.php` comentar o quitar la [linea 12](https://github.com/jmueller17/Aixada/blob/master/php/ctrl/SmallQ.php#L12) 
   * Donde dice: `include(__ROOT__ . "php/external/mpdf54/mpdf.php");`.
 * Paginas afectadas donde ya no funcionará "*Descargar PDF*" (usarla va provoca un error): 
   * `report_shop_ufs.php`: las facturas de compras 
   * `incidents.php`: los incidentes.

Propuesta definitiva: Dejar de soportar "*Descargar PDF*" para PHP-7 o en general.

@jmueller17 : ¿Qué solución ves mejor? 
 1. la radical de quitar `php/external/mpdf54` y quitar la opción del desplegable "*Descargar PDF*" en las dos páginas mencionadas. Yo soy partidario de esta, ya que actualmente solo dos de los informes ofrecen la opción de PDF y la cosa quedará limpia y coherente. 
 2. la suave de desactivar las opción solo para servidores con PHP-7.
 3. Que alguien *que no sea yo* se dedique a probar nuevas versiones de **mPdf**

**Comment by thewaywest** [comment]
@jorix : gracias!

acutalmente vivo c/ Trusty downgrade php5, quedamos allá. Todos estan de vacaciones ahora, pero voy a mencionar la propuesta de quitar relatos PDF... creo yo, no usamos, pero no tengo experiencia suficiente para dar mi opinion.

Creo yo: opción dos es mejor para el codestream. Si hay mucho interese en relatos PDF, alguien va a investigar y solucionar para nosotros (quien sabe, un futuro yo?).

**Comment by jorix** [comment]
La reflexió segueix a #234

**Comment by jorix** [comment]
Resuelto en `master`!!  
( con #248 y #249 )

**Comment by jmueller17** [comment]
Thank you!!
