### ISSUE TITLE
Use composer

### ISSUE THREAD

**Issue by davidromani** [jmueller17/Aixada#208]
Hi.

It would be interesting to manage external libraries and dependencies with this tool https://getcomposer.org

There are a huge PHP projects using it.

**Comment by naoisegolden** [comment]
@davidromani from what I have seen in the project (some time ago), a first step prior to this is to refactor the whole code base to a more module-oriented architecture. While the intention is a good one, it is far from being able to use Composer at the moment (if I am not mistaken).

**Comment by davidromani** [comment]
Composer can load external libraries into a vendor, lib or whatever directory. Then this libraries can be autoloaded. Maybe it's no so hard as it seems.

**Comment by situplastik** [comment]
It could be great to have composer but in this case, I think that bothers more than help. To use composer you must have php in computer and more things depending of your OS. I think the system has to be more portable, simple and easy to install as possible.

**Comment by davidromani** [comment]
Well, you can include composer.phar inside Git repository if you want. In my opinion, pros are higher than cons.

Enjoy :)
