### ISSUE TITLE
Problemes al importar arxius sql

### ISSUE THREAD

**Issue by mamuts** [jmueller17/Aixada#218]
Bones!

He mirat d'instalar Aixada i m'he trobat que a l'arxiu aixada.sql a la línia 85 falta una coma de finalització i provoca un error al importar l'arxiu.

Per altra banda al importar aixada_insert_default_user.sql em dona el següent error:

SQL query:

-- create accounts --
INSERT INTO aixada_account( account_id, quantity, payment_method_id, currency_id, description, operator_id, ts, balance )
VALUES (
-3, 0, 11, 1, 'cashbox setup', 1, now( ) , 0
), (
-2, 0, 11, 1, 'consum setup', 1, now( ) , 0
), (
-1, 0, 11, 1, 'maintenance setup', 1, now( ) , 0
), ( 1001, 0, 11, 1, 'admin account setup', 1, now( ) , 0 ) ;

MySQL said: Documentation
#1452 - Cannot add or update a child row: a foreign key constraint fails (`aixada`.`aixada_account`, CONSTRAINT `aixada_account_ibfk_2` FOREIGN KEY (`payment_method_id`) REFERENCES `aixada_payment_method` (`id`)) 

On pot ser el fallo?

Salut i merci!

**Comment by jorix** [comment]
> ...a la línia 85 falta

Ups!, sí falta una coma (error meu) Proposaré un PR per arreglar-ho. GRÀCIES!

> ...al importar aixada_insert_default_user.sql em dona el següent error:

Comprova que hagis importat prèviament el procediment `sql/setup/aixada_insert_defaults.sql`

**Comment by jmueller17** [comment]
Thanks!
