### ISSUE TITLE
AJAX error in login view

### ISSUE THREAD

**Issue by davidromani** [jmueller17/Aixada#223]
Just moved my Aixada instance to a new server with PHP5.6 (for now) and MySQL 5.7 and now I'm getting this new error message.

The error appears very soon, without login form submit. What can I do to debug it?

<img width="485" alt="captura de pantalla 2018-04-23 a les 20 31 10" src="https://user-images.githubusercontent.com/698779/39145991-bff2fed8-4735-11e8-9129-aa5e90b651d5.png">

**Comment by jorix** [comment]
Have you restored the database procedures? 

Do it!

or execute the procedure [sql/setup/aixada_queries_all.sql](https://github.com/jmueller17/Aixada/blob/master/sql/setup/aixada_queries_all.sql)  
(be careful if you are not using an updated version)

**Comment by davidromani** [comment]
hola @jorix 

perdona, tengo una duda... para restaurar los procedimientos de la base de datos, solamente tengo que ejecutar el script SQL?

**Comment by situplastik** [comment]
You can execute the sql that jorix said or make a migration of the old database with "structure, data & procedures", not only structure/data ;)

**Comment by davidromani** [comment]
it works!
