### ISSUE TITLE
Error manage my settings, new installation

### ISSUE THREAD

**Issue by dmanubens** [jmueller17/Aixada#225]
Hello,

After a new installation of aixada (master branch) the front end fails when logging in as admin, in the settings page. Attached screenshot.
Do you know what could be happening?

Cheers
![screenshot from 2018-04-27 20-27-31](https://user-images.githubusercontent.com/1502044/39378959-1e5f5fc6-4a5a-11e8-882d-9251faa89fa1.png)

**Comment by dmanubens** [comment]
Maybe it is related, but I cannot change theme or language, see screenshot:
![screenshot from 2018-04-27 20-33-45](https://user-images.githubusercontent.com/1502044/39379050-61a0991c-4a5a-11e8-8f04-f682fde56390.png)

**Comment by situplastik** [comment]
Looking the first screenshot, it looks like that some AJAX petition is failing (If the error 500 was during the render process, the error would show the typical Error 500 page, I think). When this page is loading, there is 4 AJAX petition (at least in my version):
- ./php/ctrl/SmallQ.php?oper=configMenu&user_role=Hacker%20Commission
- ./php/ctrl/UserAndUf.php?oper=getMemberInfo....
- ./php/ctrl/SmallQ.php?oper=getExistingLanguages.....
- ./php/ctrl/SmallQ.php?oper=getExistingThemes....

All 4 works good for you? You can check it in Firefox opening the "inspector", on the tab "Network" and filtering by "XHR" :) Connecting the 2 screenshots, the 2 last petitions that I said are related to Languages and Themes... suspicious... ^^

In any case, can you provide the PHP / MySQL / etc version ?

**Comment by jorix** [comment]
@dmanubens: 
¿Usas PHP-7? Prueba con este cambio 0e4683103dc724d50b5b679e4cb1deb390eba9c7 , pero ten en cuenta que nadie de Aixada (que yo sepa) se ha puesto en producción en ese territorio hostil ;-)

NOTA: Los síntomas que cuenta te comenta @situplastik son típicos de PHP7.  Si no es eso dilo y seguiré mirando.

**Comment by dmanubens** [comment]
You're right @situplastik, 3 of the 4 AJAX petition fail, Languages, Themes and user_role. See screenshot:
Indeed, I use `MySQL 5.7.22-0ubuntu0.16.04.1` and `PHP Version 7.0.28-0ubuntu0.16.04.1`. Sorry @jorix , I did not read the wiki warning about PHP-7 not being supported. I will try downgrading to PHP-5. However, I am keen to test patches for PHP-7 if it can help. I'll try 0e4683103dc724d50b5b679e4cb1deb390eba9c7 and let you know. 
![screenshot from 2018-04-28 11-01-49](https://user-images.githubusercontent.com/1502044/39394794-69bf67dc-4ad6-11e8-8a89-078da1961c1b.png)

**Comment by dmanubens** [comment]
Hola @jorix el cambio que propenes evita los errores que he mencionado. Segun lo que dices en el commit, la impresion en PDF no va a funcionar y quizas algunas cosas más. He seguido los primeros pasos: https://github.com/jmueller17/Aixada/wiki/Primeros-pasos-administrador---creador-de-pedidos y he podido crear UFs, usuarios y proveedores, pero no productos (ni imp.rev, iva, unidades). Recomiendas que me pase a PHP 5?

**Comment by jorix** [comment]
Si

El ds., 28 abr. 2018 12.14, Domingo Manubens Gil <notifications@github.com>
va escriure:

**Comment by dmanubens** [comment]
Ok with PHP-5.6 it works! thank you!
