### ISSUE TITLE
Error 1406 (data too long for column 'products') on get_member_info call

### ISSUE THREAD

**Issue by davidromani** [jmueller17/Aixada#226]
Al acceder a la ruta `/manage_mysettings.php` me aparece el siguiente error:

`CALL get_member_info('2','0') generated error 1406: Data too long for column 'products' at row 27`

Existe alguna manera de alterar alguna tabla (o columna) para solucionarlo?

**Comment by jorix** [comment]
>Existe alguna manera de alterar alguna tabla (o columna) para solucionarlo?

Sí, como parche provisional esto funcionará y no se pierde nada relevante:
```sql
delimiter |
drop function if exists get_products_of_member|
create function get_products_of_member(the_member_id int)
returns varchar(255)
begin
  declare products varchar(255);
  return '';
end|
```
Este procedimiento UNICAMENTE se usa para mostrar la lista truncada de los productos de los que es responsable la UF del miembro.
Dejarà de mostrarse esta información de la cuenta:
![imagen](https://user-images.githubusercontent.com/1099278/39424280-2ada29e8-4c76-11e8-9826-34015a5eacc2.png)

**Comment by jorix** [comment]
Pero voy a investigar más...  
Primero ver sí está relacionado con el uso de `character_set_database=latin1` (pensando en #224). Yo me inclino a que sí, pero por ahora no he montado el entorno para probarlo.

**Comment by davidromani** [comment]
@jorix ya he alterado toda la BD para canviar a UTF8 y su colación correspondiente. También he ejecutado SQLs para convertir el contenido existente en todas las tablas.

Lo puedes ver aquí:

```sql
Server version: 5.7.22-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show variables like "character_set_database";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| character_set_database | utf8  |
+------------------------+-------+
1 row in set (0.00 sec)

mysql> show variables like "collation_database";
+--------------------+-----------------+
| Variable_name      | Value           |
+--------------------+-----------------+
| collation_database | utf8_general_ci |
+--------------------+-----------------+
1 row in set (0.00 sec)
```

**Comment by jorix** [comment]
Y habeis ejecutado otra vez aixada_queries_all.sql?

Es importante hacerlo.


El dl., 30 abr. 2018 15.55, David Romaní <notifications@github.com> va
escriure:

**Comment by davidromani** [comment]
Sí, también lo he hecho.

**Comment by jorix** [comment]
Ok, pues partiré de ahí cuando me ponga hacer pruebas.


El dl., 30 abr. 2018 16.12, David Romaní <notifications@github.com> va
escriure:

**Comment by davidromani** [comment]
Hola, perdona que insista @jorix 

Has podido solucionar algo de este tema?
