### ISSUE TITLE
bill model and order model does not display lines

### ISSUE THREAD

**Issue by dmanubens** [jmueller17/Aixada#229]
When I select a cart from the list, to show its details, the report_shop_ufs shows correctly, but when I click on print on new window, or download PDF, the details don't show up.

See screenshots:
![screenshot from 2018-07-09 07-46-50](https://user-images.githubusercontent.com/1502044/42432768-960c3816-834c-11e8-9664-ee234082a3fd.png)
![screenshot from 2018-07-09 07-46-26](https://user-images.githubusercontent.com/1502044/42432769-96338a06-834c-11e8-8b5e-050792094bbf.png)

It happens the same when I click on the small printer button on top of each order at 'my orders'.
Note that UF info is not shown correctly either.

![screenshot from 2018-07-09 07-50-58](https://user-images.githubusercontent.com/1502044/42432831-eb42fb12-834c-11e8-867b-67958a7b115c.png)
![screenshot from 2018-07-09 07-51-04](https://user-images.githubusercontent.com/1502044/42432830-eb230550-834c-11e8-8bd2-c3f2b74931c9.png)

@jorix could you help on that?
Thanks a lot in advance

**Comment by dmanubens** [comment]
PDF report does not work at all, should I create a new issue?

**Comment by jorix** [comment]
Este nuevo PR #230 lo arregla, faltaba cargar una herramienta js el los listados.

NOTA: He comprobado que el generador PDF falla en PHP 5.5 pero funciona en PHP 5.3  
(el problema es a causa del codigo PHP la herramienta externa que usa Aixada para generar PDF)  
Así pues mejor no usar el "descargar PDF". 

NOTA2: Yo no tengo previsto de arreglar la generación en PDF para PHP 5.5 o superios, ya que hay otra vías para obtener el informe y puede ser complicado encontrar una nueva versión de la herramienta que funcione para todas las versiones PHP en que corre Aixada

**Comment by dmanubens** [comment]
Genial, muchas gracias @jorix ! mas tarde lo pruebo.
