### ISSUE TITLE
Importar la base de dades a un nou servidor

### ISSUE THREAD

**Issue by mamuts** [jmueller17/Aixada#235]
Bones,,

Estic mirant d'actualitzar la versió que utilitzavem a la última que hi ha pels problemes de compatibilitat amb php7. He fet una còpia de la base de dades amb phpmyadmin per importar les dades a la nova web. Però al restaurar l'arxiu sql em dona errors de privilegi:

consulta SQL:

--
-- Database: `saltioliorg`
--
DELIMITER $$--
-- Procedures
--
CREATE DEFINER = `saltioliorg`@`%` PROCEDURE `activate_preorder_products` ( IN the_date date, IN product_id_list varchar( 255 ) ) BEGIN SET @q = concat( "update aixada_order_item
          set date_for_order = '", the_date, "' where date_for_order = '1234-01-23'
	    and product_id in ", product_id_list, ";" ) ;

prepare st FROM @q ;

EXECUTE st;

deallocate prepare st;

end$$

MySQL ha dicho: Documentación
#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation 

Quan si que tinc permisos sobre la base de dades. Quina és la millor opció per migrar de host i de versió de l'aixada?

Merci per endavant! I perdo per tanta pregunta ;)

**Comment by jorix** [comment]
>...compatibilitat amb php7...

Aixada, per ara, **no funciona** en PHP >=7.1. En 7.0 es pot fer alguna cosa però ni hi ha garanties.

>...CREATE DEFINER = saltioliorg@% PROCEDURE activate_preorder_products...

Tens drets sobre l'esquema `saltioliorg`?

**Comment by mamuts** [comment]
Bones, al final vaig trobar com poder fer la migració de host. He aprofitat i he escrit una còpia, a partir del que hi havia a la wiki de com fer la instalació, però pensat en com fer una migració de host. 

**Migració de host (utilitzant phpMyAdmin)**

- Descarrega tots els arxius de l'última actualització al teu ordinador.

- Edita l'arxiu de configuració del teu servidor actual local_config/config.php i actualitza els camps db_name, db_user, db_password amb les dades de la base de dades del nou host que faràs servir. Si estàs instal·lant una versió diferent és millor que creïs un nou arxiu config.php renombrant l'arxiu config.php.sample i modificant les dades per defecte per les dades del teu nou hosting.

- Puja  tots els arxius al nou servidor, si és possible amb un client que permeti sFTP, si utilitzes un client d'FTP normal, els enllaços simbòlics es perdran. Al final s'explica com solventar aquest error.
Accedeix a phpMyAdmin en el teu host actual i clica sobre la base de dades que estiguis utilitzant actualment. Selecciona la pestanya ''Exportar''. Clica sobre la opció ''Usuari - mostra totes les opcions possibles''. Dins les opcions que es despleguen selecciona totes les taules. Escull el nom de l'arxiu que es crearà. Escull l'opció ''Estructura i dades''. Deselecciona les opcions ''Afegir instrucció CREATE PROCEDURE / FUNCTION / EVENT'' i l'opció ''AUTO_INCREMENT''. Es crearà un arxiu en format sql amb totes les taules i dades.

- Accedeix a phpMyAdmin del nou host on vulguis treballar. Crea una base de dades amb l'ordenació: utf8_general_ci. Selecciona la base de dades que acabes de crear i clica sobre la pestanya ''Importa''. 

- Selecciona  l'arxiu que hem exportat anteriorment i importe'l.

- Si estàs actualitzant l'aplicatiu és possible que necessitis importar també l'arxiu:

sql/setup/aixada_queries_all.sql

- Comprova  que els següents directoris tenen permisos d'escriptura. Amb el cliente d'FTP FileZilla, fes clic sobre el directori i selecciona la opció Permisos d'arxiu:

local_config/dbBkups/
local_config/reports/
local_config/orders/

- Si el teu servidor no és compatible amb sFTP tindràs que renombrar alguns arxius perquè els  enllaços simbòlics es perden al carregar-los per FTP normal. En cas de dubte, obre l'explorador d'Internet i ves al directori d'instalació d'Aixada. Si la pàgina no es veu correctament, amb un requadre d'inici de sessió, renombra els següents arxius:

1. js/jquery/jquery-1.7.1.min.js -> js/jquery/jquery.js 
2. js/jqueryui/jquery-ui-1.8.20.custom.min.js -> js/jqueryui/jqueryui.js 
3. css/ui-themes/redmond/jquery-ui-1.8.20.custom.css -> css/ui-themes/redmond/jqueryui.css 
4. css/ui-themes/start/jquery-ui-1.8.20.custom.css -> css/ui-themes/start/jqueryui.css 
5. css/ui-themes/ui-lightness/jquery-ui-1.8.20.custom.css -> css/ui-themes/ui-lightness/jqueryui.css 
6. css/ui-themes/smoothness/jquery-ui-1.8.20.custom.css -> css/ui-themes/smoothness/jqueryui.css

**Comment by jorix** [comment]
He fet una cosa més resumida a [wiki](https://github.com/jmueller17/Aixada/wiki/Actualizaci%C3%B3n).

Allà també parla de la nova actualització automàtica.

**Comment by jorix** [comment]
Ah!, i gràcies!
