### ISSUE TITLE
Issues with "date format" in MySQL if "strict mode" is active

### ISSUE THREAD

**Issue by mbenito** [jmueller17/Aixada#261]
Some hosts are activating the strict mode in the MySQL server and many problems with date format are being prompted.

**Comment by jorix** [comment]
Try using the current `master` with the recent PR #257

**Comment by jorix** [comment]
@mbenito Please report the result of current `master` if it has been positive.  
( otherwise, too, of course! )

**Comment by mbenito** [comment]
Great! It works! I have applied this solution:

    $this->mysqli->query("SET @@SQL_MODE = ' ';");
    $this->mysqli->query("SET @@group_concat_max_len = 255;");

Thanks a lot for you help and your contribution!
