### ISSUE TITLE
Using HTTPS on v2.8. Error loading orders on index.php

### ISSUE THREAD

**Issue by vviudez** [jmueller17/Aixada#263]
Forcing to use HTTPS on our aixada site, we found this error:

![image](https://user-images.githubusercontent.com/4720407/61079912-2a7b1c80-a424-11e9-811e-7d605d86b26e.png)

Using HTTP works fine.

The past orders seems to be loaded correctly, but for some reason, are not printed on the page, until you click the back button from the table a couple of times.

**Comment by jorix** [comment]
Sería bueno centrar un poco más el error...

En el navegador (chrome, FF ...) activa las herramientas para desarrolladores (con la tecla *F12*), situate en el apartado **Network** y filtra por **XHR**. 

Carga la pagina que falla (te refiere a index.php?) de nuevo.  
Allí han de aparecer todas la URL consultadas a los controladores de vuestro Aixada. Mira los errores, ¿que URL de `php/ctrl/` falla?

**Comment by vviudez** [comment]
Ocurre con cualquier navegador que he probado.
Analizando un poco, parece que el problema venia de usar jquery 1.9.... al usar la libreria de la versión 1.7.1, todo parece funcionar.

Sigo testeando, por si acaso.

**Comment by jorix** [comment]
> ... al usar la libreria de la versión 1.7.1, 

Ok, entendido.  
Sí! Aixada está probado con la 1.7.1
