### ISSUE TITLE
Instalación de Aixada: Descarga de dónde

### ISSUE THREAD

**Issue by narcisgarcia** [jmueller17/Aixada#264]
Como primer paso está documentado: «Descarga todos los archivos Aixada a al directorio de tu servidor...»
¿Cual es el enlace u origen correcto para descargar un paquete estable del software?

Además, hay 29 derivados; ¿Es la rama «master» la más adecuada?

**Comment by jorix** [comment]
> ¿Cual es el enlace u origen correcto para descargar un paquete estable del software?

La rama `master` de `jmueller17/Aixada`.
(*También hay casos que han usado la rama [jorix/laCistella-master](https://github.com/jorix/Aixada/tree/laCistella-master), que es la `jmueller17/master` con algunos informes más para reparto usando papel*)

He cambiado la información en [Instalación](https://github.com/jmueller17/Aixada/wiki/Instalación), ahora ya está como en [Actualización](https://github.com/jmueller17/Aixada/wiki/Actualización).

**Comment by narcisgarcia** [comment]
¿Se podría mencionar en la guía las variantes (soportadas) posiblemente útiles a descargar?
Tales como la rama jorix/laCistella-master mencionada.

**Comment by narcisgarcia** [comment]
(habiendo hecho una instalación de «master» no sé cómo es adecuado actualizarla a "jorix/laCistella")

**Comment by jmueller17** [comment]
Diría que el master de Aixada tiene todos los parches de jorix. Asi debería ser lo mismo.

**Comment by jorix** [comment]
> (habiendo hecho una instalación de «master» no sé cómo es adecuado actualizarla a "jorix/laCistella")

Pues debes copiar el contenido en de `jorix/laCistella-master` sobre lo que tengas.

Luego debes ejecutar el `sql/_cistella.sql`, este paso no está automatizado para LaCistella

Como dice @jmueller17 en `jmueller17/master` hay los mismos parches que en `jorix/laCistella-master`. Solo cuando hay algun PR de parches en danza puede haber una rama que lo tenga y la otra no.

>Asi debería ser lo mismo.

No, no es exactamente lo mismo, hay la lista de turnos previstos y algunos informes en *jorix* que no están en *jmueller17*. Eran cosas que pensé que eran muy particulares de laCistella, pero que luego alguna otra coope ha optado por poner.

**Comment by narcisgarcia** [comment]
Gracias.
