### ISSUE TITLE
Feature request: Dark theme

### ISSUE THREAD

**Issue by narcisgarcia** [jmueller17/Aixada#266]
Changing interface theme is not always for aesthetic reasons. There are other rational reasons, such as website integration, energy saving or ocular health.
This extends to visitors interface and defaults for new users.

**Comment by jorix** [comment]
Currently I only have in mind spending time in Aixada if stability problems appear.

**Comment by jmueller17** [comment]
Narcis, would be great if you contribute!

**Comment by narcisgarcia** [comment]
jorix' response was enough consistent for me.
There are many ways to contribute; I hope someone else can work on this feature request. In the meanwhile I spread FOSS usage and teaching, and I often make the effort to feed back to developers.
