### ISSUE TITLE
Dockerization needs some improvements

### ISSUE THREAD

**Issue by eduponte** [jmueller17/Aixada#267]
1. When running from docker we found some errors, caused by `mysqli` missing.
2. In addition, `Dockerfile` was difficult to find, so I'm wondering wether it could be moved to the root level.
3. A `docker-compose` with the DB and `phpmyadmin` would be helpful for a completely dockerized environment.

I am creating a PR for these issues.

**Comment by situplastik** [comment]
I'm not sure if this project need dockerization. As fas as I concern, one of the main priorities of Aixada is to be as easy as we can in order not to need technical knowledge. It would be grateful if apart of preparing the project, adding some explanation in readme (for helping people): telling a little bit the docker philosophy and distincting the basic installing option and the docker installing option.

We have to keep in mind that many people who implement and maintains the system on theirs association aren't IT and don't have time to invest neither interest.

Nonetheless, I have to say that I :heart: the contribution ;)

**Comment by eduponte** [comment]
Docker is not a mandatory technology, it's something you can take advantage of, in case you want to quickly spawn a local environment, either for developing or testing the tool (which was our case).
I agree that adding some documentation would be great, though it would take some more time.
