### ISSUE TITLE
Aclariment 'Fes la teva compra' vs 'Propera comanda'

### ISSUE THREAD

**Issue by Monicafgz** [jmueller17/Aixada#273]
Bones,
Tenim el dubte de quins productes apareixen quan accedim des de la pàgina d'inici a 'Festa teva compra' o bé a 'Propera comanda'.
Entenem que a la primera opció apareixeran només els productes que a l'hora d'afegir-los seleccionem de tipus stoc, mentre que a l'opció 'Propera comanda' només apareixeran els productes tipus 'comanda directa', es així?
Gràcies!
Mònica

**Comment by jorix** [comment]
@Monicafgz 

Per defecte no!, però ports configurar-ho:  
*Solo permitir productos de stock en compras (💡config.php: $use_shop='only_stock')*

NOTA: A [CHANGELOG-es.md](https://github.com/jmueller17/Aixada/blob/master/CHANGELOG-es.md) hi ha recollits els canvis des de 2015 amb una referencia "💡" quan tenen parametres asociats de `config.php`

**Comment by Monicafgz** [comment]
Amb aquest canvi ja ens funciona perfectament!
Gràcies!
Mònica
