### ISSUE TITLE
Asignación de responsables de proveedor

### ISSUE THREAD

**Issue by Monicafgz** [jmueller17/Aixada#274]
A la hora de asignar responsables de un proveedor, Aixada tiene la opción de asignarle una Unidad Familiar (UF), pero sería posible asignar a un mismo proveedor varias UF responsables?
Gracias!

**Comment by jorix** [comment]
Ups!, que yo sepa no hay gente desarrollando nuevas prestaciones de Aixada.  
En su momento lo que hacíamos en nuestra coope era añadir a la UF responsable tantos miembros (ficticios) como CC de emails nos interesaba recibir de los pedidos solicitados a un proveedor.

Sí!, estaría bien lo que propones, o casi mejor que fueran los miembros y no los UF los multi-responsables.
