### ISSUE TITLE
Añadir nueva categorías de productos

### ISSUE THREAD

**Issue by Monicafgz** [jmueller17/Aixada#276]
El programa permite añadir nuevas categorías de productos además de las que tiene por defecto?
No encontramos la categoría de "llegums".
Otra posibilidad es cambiar alguna de las categorías que no usamos por esta, pero qué archivos se han de modificar en tal caso?

$Text['prdcat_vegies']		 	= "Verdures";
$Text['prdcat_fruit'] 			= "Fruita";
$Text['prdcat_mushrooms'] 		= "Bolets";
$Text['prdcat_dairy'] 			= "Llet i iogurts"; 			//llet fresca, iogurt
$Text['prdcat_meat'] 			= "Carn";							//pollastre, vedella, xai/corder, etc.
$Text['prdcat_bakery'] 			= "Productes de forn i farina";						//pa, pastes, farina
$Text['prdcat_cheese'] 			= "Formatge";
$Text['prdcat_sausages'] 		= "Embotits";					//pernil, botifarres, etc.
$Text['prdcat_infant'] 			= "Nutrició infantil";
$Text['prdcat_cereals_pasta']	= "Cereals i pasta";	//cereals i pasta
$Text['prdcat_canned'] 			= "Conserves";
$Text['prdcat_cleaning'] 		= "Neteja";					//neteja de la llar, detergents, etc.
$Text['prdcat_body'] 			= "Productes corporals";
$Text['prdcat_seasoning'] 		= "Adobs i algues";
$Text['prdcat_sweets'] 			= "Mel i dolços";		//melmelada, mel, sucre, xocolata
$Text['prdcat_drinks_alcohol'] 	= "Begudes alcohòliques";			//vi, cervesa, etc.
$Text['prdcat_drinks_soft'] 	= "Begudes no alcohòliques";			//suc, begudes vegetals
$Text['prdcat_drinks_hot'] 		= "Cafè i te";
$Text['prdcat_driedstuff'] 		= "Coses per a picar i fruits secs";
$Text['prdcat_paper'] 			= "Cel·lulosa i paper";		//mocadors, paper del vàter, paper de cuina 
$Text['prdcat_health'] 			= "Salut";		//paper del vàter, paper de cuina 1
$Text['prdcat_misc']			= "Tota la resta..." ;

Gracias!

**Comment by jorix** [comment]
No està previst, heu d'afegir la categoria via sql i també als 3 arxius d'idioma d'Aixada.

```sql
INSERT INTO aixada_product_category(id, description) VALUES ('30001', 'prdcat_llegums');
```
feu servir com `id` el 30001 en endavant.

i posar afegir a
* `es.php`
```php
$Text['prdcat_llegums'] = "Las legumbres";
```
* `ca-va.php`
```php
$Text['prdcat_llegums'] = "Els llegums";
```
* `en.php`
```php
$Text['prdcat_llegums'] = "The legumes";
```

Si us decanteu per canviar el text d'una que ja existeix, jo us aconsello afegir l'assignació a final de cada arxiu d'idioma amb la vostra traducció, d'aquesta manera quedarà sobreescrit el text d'Aixada... I així **en un futur** sabreu que teniu tots els vostres texts al final del arxius d'idioma d'Aixada i us serà més fàcil una hipotètica actualització.

**Comment by Monicafgz** [comment]
Ens funciona! moltes gràcies per l'explicació!

**Comment by Monicafgz** [comment]
Només un dubte, quin es el motiu d0'aquest comentari
> feu servir com id el 30001 en endavant.

Gràcies de nou!

**Comment by jorix** [comment]
> Només un dubte, ...

Al instalar la taula ja té dades fins el `id` *22000*, així que per evitar entrar en conflicte amb les categories ja instal·lades us vaig proposar usar a partir del *30001* per les vostres.

**Comment by Monicafgz** [comment]
Entesos, gràcies @jorix
