### ISSUE TITLE
Problemes a l'importar

### ISSUE THREAD

**Issue by joancortes** [jmueller17/Aixada#279]
Hola!

Sóc del grup de consum A Pas de Cargol, de Llagostera (el Gironès), i estem implementant l'Aixada, la branca de la Cistella, per gestionar les compres conjuntes del col·lectiu. A l'hora de començar a importar els productes, ens dóna el següent error:

![image](https://user-images.githubusercontent.com/24567043/92441958-68520d00-f1af-11ea-9723-215f12d0434a.png)

L'arxiu on tenim totes les dades i intentem importar és el següent: [fundOnyar.xlsx](https://github.com/jmueller17/Aixada/files/5186536/fundOnyar.xlsx).

Desconec si és un error de format de l'arxiu o un problema del servidor on està allotjat el programari (un NAS personal). Gràcies.

**Comment by jorix** [comment]
He provat. Sí, sembla que els `.xlsx` no funcionen del tot, aquest no em va.

Convertit a altres formats sí que funciona:  
 * En `.xls` i `.txt` (separant camps per tabuladors) funcionen correctament
 * En `.ods` (open document) va, però no detecta correspondències dels noms de columnes
 * En `.csv` hi ha problemes amb els accents (Excel exporta en ANSI però la importació ho espera en la codificació CMD)

NOTA: La importació utilitza un programari de tercers que no està massa actualitzat, per ara mireu d'usat els formats que sí que funcionen.  
(@jmueller17 Esto sería un tema pendiente)

**Comment by joancortes** [comment]
He provat en `.xls` i `.txt` (separant camps per tabuladors) i segueix donant el mateix error. Pot ser cosa de la codificació en la que guardo els arxius? O és un problema del servidor?

**Comment by jorix** [comment]
Podria ser falta d'autorització a la carpeta `local_config\upload`, l'usuari que executa el servei PHP ha de ternir-hi autorització.  
(al treure autorització en el meu servidor de proves mostra un missatge *Unexpected token in JSON* com el vostre)

Pots veure el missatge detallat fent debug (normalment amb F12) a la finestra de la importació, ho heu de fer abans de seleccionar l'arxiu i mirar què apareix a l'apartat xarxa. Si tot va bé contesta un JSON, però si falla alguna cosa del servidor contesta un arxiu de text.

**NOTA**: Aixada escriu coses a les carpetes:  
* `local_config`  (Informes evolució en SVG)
* `local_config/dbBkups` 
* `local_config/debug_mail` 
* `local_config/export` 
* `local_config/orders` (no conec perquè es fa servir, per si un cas...)
* `local_config/reports` (no conec perquè es fa servir, per si un cas...)
* `local_config/upload`

**Comment by joancortes** [comment]
Correcte. Es tractava d'un tema de permisos de la carpeta `local_condig\upload`... Ara ja funciona correctament.

Mil gràcies per l'ajuda prestada!
