### ISSUE TITLE
Fatal error:  Array and string offset access syntax with curly braces  is no longer supported in

### ISSUE THREAD

**Issue by VictorJavaSpring** [jmueller17/Aixada#288]
Algú sap a què pot ser degut l'error següent, sisplau? Gràcies.
Fatal error: 
Array and string offset access syntax with curly braces 
is no longer supported in 
/customers/2/d/4/girasoldesantmarti.net/httpd.www/aixada/php/external/FirePHPCore/lib/FirePHPCore/
FirePHP.class.php 
on line 1093

**Comment by jorix** [comment]
Veig que es a causa del PHP 7.4, canvieu la linia 1093 del `aixada/php/external/FirePHPCore/lib/FirePHPCore/
FirePHP.class.php` on diu `if ($name{0} == "\0") {` per 
```PHP
          if ($name[0] == "\0") {
```

@jmueller17: Se debería actualizar el FirePHP o eliminar su uso, yo casi me decantaria por lo segundo, ¿que opinas?

**Comment by jorix** [comment]
veure https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated

**Comment by victorcillo** [comment]
Perdoneu la meva ignorància.. hem pregunto si algú pujarà la correcció/ns, perqué tenim l'aplicació parada per fer comandes.. que ens recomaneu? Gracies

**Comment by jmueller17** [comment]
Sí, lo eliminamos mejor. A ver si tengo un momento hoy...

**Comment by jorix** [comment]
@victorcillo 

* Has prova de fer el canvi a la línia `1093` de `aixada/php/external/FirePHPCore/lib/FirePHPCore/ FirePHP.class.php`?

@jmueller17 
> Sí, lo eliminamos mejor. A ver si tengo un momento hoy...

Lo puedo hacer yo, y propongo PR

**Comment by jmueller17** [comment]
Ok, genial!

**Comment by jorix** [comment]
@victorcillo 

> Perdoneu la meva ignorància.. hem pregunto si algú pujarà la correcció/ns, perqué tenim l'aplicació parada per fer comandes.. que ens recomaneu? Gracies

Els canvis ja estan a `master`. Si us plau notifiqueu com us va quan ho proveu, gràcies

**Comment by victorcillo** [comment]
Deixa fer Log in, pero la part de demanar comandes falla, per pantalla surt així:
![WhatsApp Image 2022-01-16 at 22 02 33](https://user-images.githubusercontent.com/13764287/149678052-5af0fc99-194a-47f3-8b8c-d3510136bb4e.jpeg)

**Comment by jorix** [comment]
> Deixa fer Log in, pero la part de demanar comandes falla, per pantalla surt així...

Fa pinta de que hi ha més problemes amb la versió PHP 7.4, mireu d'usar **una versió inferior de PHP**.

Faré una prova del cicle de comandes i diners amb la 7.4.26, i ja posats amb la 8.1.1. Requerirà cert temps per poder dir alguna cosa...

**Comment by jorix** [comment]
Mira #290, arregla un error greu meu que feia que res funciones!!

Però amb amb el PHP 8.1 usant aquest PR  Aixada només va a mitges (encara no he fet proves del PHP 7.4)

Ara amb PHP 8.1 encara no funciona Importar/exportat i se suposa que tampoc els emails

**Comment by victorcillo** [comment]
He probat amb #290 pero segueix sense mostrar les productes per demanar comanda, encara no hem canviat versió del PHP..

**Comment by jorix** [comment]
> He probat amb #290 pero segueix sense mostrar les productes per demanar comanda, encara no hem canviat versió del PHP..

Ho havia provat amb PHP 8.1.1, i ara amb PHP 7.4.27

El #290 em funciona!!!  
(ara #290 està també a `master`)

També em funciona amb PHP 5.5.22

- - - - -

Ara que m'hi fixo aquesta **pantalla** indica que no has usat `install.php`
( és la típica pantalla d'Aixada sense `*.js` ni `*.css` , si tens un servidor windows el procés `install.php` també arregla un links que linux enten bé però windows no )


> Deixa fer Log in, pero la part de demanar comandes falla, per pantalla surt així: ![WhatsApp Image 2022-01-16 at 22 02 33](https://user-images.githubusercontent.com/13764287/149678052-5af0fc99-194a-47f3-8b8c-d3510136bb4e.jpeg)

**Comment by jorix** [comment]
@victorcillo A pesar del #290 si vols fer imports, fer exports o envia missatges no treballis amb PHP 7.4 o superior!

**Comment by victorcillo** [comment]
Acabo de canviar la versió PHP a 4.7 en el servidor on tenim allotjada la aplicació i sembla que torna a funcionar..
![PHP4_7](https://user-images.githubusercontent.com/13764287/150642881-cc2931be-f18e-41f9-9bd0-9d700d062ab8.jpg)
Encara que sembla que la versió PHP 7.4 acaba el 22 de noviembre de 2022.
Tot i aixó, he vist uns errors accedint a la secció diners a l'archiu "accounts_operations.php":
![error_22_1](https://user-images.githubusercontent.com/13764287/150643223-ce3081c6-033c-40a0-868e-2726f501bc04.jpg)
![error_22_2](https://user-images.githubusercontent.com/13764287/150643230-bc24cf72-31ff-4e62-bd93-89a3c6f8f58a.jpg)
Salud!

**Comment by jorix** [comment]
@victorcillo Usa com a mínim el  PHP 5.3!!!!

A la wiki ja ho indica:
> PHP 5.3.2 or newer and PHP-7 (tested up to v7.3)

Estic treballant per que funcioni fins a la actual versió de PHP 8.2.1

**Comment by victorcillo** [comment]
Perdona, m'he equivocat al ficar el numeret de la versió! 
He actualitzat a 7.4  ( no a 4.7)

**Comment by victorcillo** [comment]
https://stackoverflow.com/questions/32559674/in-array-expects-parameter-2-to-be-array-string-given-in
Pot ser fent 1 casting a la array?
// Cast to an array
$array = (array) $account_types;

**Comment by victorcillo** [comment]
Si, fent el casting 'arregla aquest error:
		**$account_types = (array) $account_types;**

**Comment by victorcillo** [comment]
> @victorcillo A pesar del #290 si vols fer imports, fer exports o envia missatges no treballis amb PHP 7.4 o superior!

No fem imports ni exports ni enviem missatges! :)

**Comment by jorix** [comment]
> Si, fent el casting 'arregla aquest error: **$account_types = (array) $account_types;**
> 
> ```
> ...
> $account_types = (array) $account_types;  <-------
> ```
> 
> **... Faig una alftra issue amb aixó?**

No cal un altres issue.  

No he pogut reproduir el problema, però mira si usant el PR #291 s'arregla.  
( he vist que per exemple cridant `/php/ctrl/Account.php?oper=getBalances&account_types=` si fallava, però no he vist cap lloc on es pugui cridat així el `/php/ctrl/Account.php` )

Voldria saber com ho fas fallar: és una cridant a `/php/ctrl/Account.php?oper=...`? amb quins paràmetres? (suposo usant que `/manage_money.php`) però fent què?

**Comment by victorcillo** [comment]
L'error hem sortia clikant a "Diners" en concret a l'arxiu "accounts_operations.php" segons deia els popups d'error, no a Account.php, tot, a la vista "report_account.php" amb el parámetre what = "my_account" (com surt a la url de la captura):
![error_diners2](https://user-images.githubusercontent.com/13764287/150696280-ac22bc06-0628-41c9-bcf1-01eab6199eee.jpg)
He implementat el #291 per si un cas, sembla que funciona igual, estem fent proves a veure si realment funciona el fluxe de demanar comandes clickant a "Propera comanda".

**Comment by victorcillo** [comment]
Hem provat i funciona correctament de moment, Gracies a totes!

**Comment by jorix** [comment]
Dius:   
>He implementat el #291 per si un cas, sembla que funciona igual  
Vol dir que segueix fallant o que ja funciona? La pantalla que mostres es de quan funciona amb el cast `(array)`?

Si el #291 no ho arregla m'interessa saber on falla.  
Jo no ho he pogut reproduir l'error usant `/report_account.php?what=my_account` ni sense el #291

Fer un f12 al navegador i mira a xarxes les respostes en XML (n'hi ha a tres, segurament a una d'elles hi has de poder veure l'error), com l'exemple a sota.

![image](https://user-images.githubusercontent.com/1099278/150765079-53863d41-7995-4c71-97a7-7dad6bea7a68.png)

**Comment by victorcillo** [comment]
La aplicació ja funciona correctament, la captura és d'aquest estat correcte sense errors, el casting va funcionar correctament, després de fer servir la versió 7.4 de PHP al nostre servidor.
No es detecta cap error a les respostes 👍 
![sense_errors2](https://user-images.githubusercontent.com/13764287/150783620-880ba140-391b-4c98-a4fa-1f561363771e.jpg)

**Comment by jorix** [comment]
> La aplicació ja funciona correctament, la captura és d'aquest estat correcte sense errors, el casting va funcionar correctament, després de fer servir la versió 7.4 de PHP al nostre servidor. Al aplicar el #291 la aplicació seguía funcionant correctament sense canvis visibles. No es detecta cap error a les respostes 👍 

Entenc doncs que sense el casting funciona?
(PHP 7.4 amb el #291)

**Comment by victorcillo** [comment]
Doncs, com vaig comentar a https://github.com/jmueller17/Aixada/issues/288#issuecomment-1019290362, fent el casting es corregía l'error que donaba al accedir a "Diners" a la nostra aplicació.
Així que si no fiquem el casting $account_types = (array) $account_types;  a l'archiu /php/lib/account_operations.php a la funció get_account_types_filter, just avans de la declaració de la variable $_key = array_search(1000, $account_types, true); , provoca 4 errors als array_splice

**Comment by jorix** [comment]
@victorcillo Entesos, ara el #291 també inclou el cast.

**Comment by victorcillo** [comment]
Tenim un  altre error a la secció Diners, no surten els comtes a gestionar als desplegables:
![err_manage_money_2](https://user-images.githubusercontent.com/13764287/150953406-e65efcbd-2a92-4c1a-9e14-ea15000153bb.jpg)

**Comment by jorix** [comment]
> Tenim un altre error a la secció Diners, no surten els comtes a gestionar als desplegables...

Segurament no és un altre error, deu ser l'error que cast `(array)` ha amagat.
(en el meu servidor local no he pogut reproduir el problema: `master` i PHP 7.4.27)

Usa `master` (ja té el #291), així usarem el mateix codi.

Digues què et responen: 

1.  `/php/ctrl/Account.php?oper=getAccounts&all=0&account_types=1,2,1000,2000`  
2.  `/php/ctrl/Account.php?oper=getAccounts&all=0&account_types=1000`

**Comment by jorix** [comment]
Crea també aquest php com `try-get-array.php`:

```php
<pre>
<?php var_export($_REQUEST); ?>
</pre>
```

i digues que respon el `try-get-array.php?oper=getAccounts&all=0&account_types=1,2,1000,2000`

**Comment by victorcillo** [comment]
@jorix Xavi, acabo de fer un petit canvi, un gran pas a la nostra aplicació, ja que a la línia 109 la funció get_accounts_XML cridava al métode get_account_types_filter amb el parámetre d'aquesta manera: 
$account_types=''
lo que provocaba error, ja que el·liminant la assignació a cadena buida, torna a funcionar la part de Gestionar els diners i surten els comptes i UF's correctament als desplegables que fallaven...
        $filter = $this->get_account_types_filter(**$account_types=''**);
![error_22_1](https://user-images.githubusercontent.com/13764287/153058481-7190c8d9-3c5c-443a-82f5-92f4892a6f1a.jpg)

        $filter = $this->get_account_types_filter(**$account_types**);
![Screenshot_3](https://user-images.githubusercontent.com/13764287/153059106-1258f9d3-27c9-4f87-abb7-93a25354d9cc.jpg)

**Comment by jorix** [comment]
> @jorix Xavi, acabo de fer un petit canvi, un gran pas a la nostra aplicació, ja que a la línia 109 la funció get_accounts_XML cridava al métode get_account_types_filter amb el parámetre d'aquesta manera: $account_types=''...

Sí, això s'ha d'arreglar. Però pensant en PHP 8.1 s'hi ha de posar: 
* `public function get_accounts_XML($all=0, $account_types=array()) {` o 
* `public function get_accounts_XML($all, $account_types) {`

- - - 

@victorcillo Però segueixo **MOLT** preocupat per no saber reproduir el vostre error!

Si us plau fes les proves que et vaig suggerir, sobre tot aquesta:


> Crea també aquest php com `try-get-array.php`:
> 
> ```
> <pre>
> <?php var_export($_REQUEST); ?>
> </pre>
> ```
> 
> i digues què respon el `try-get-array.php?oper=getAccounts&all=0&account_types=1,2,1000,2000`

i què passa amb:  
`try-get-array.php?oper=getAccounts&all=0&account_types=1|2|1000|2000`

**Comment by victorcillo** [comment]
perdona la tardança, he estat molt liat...
el try-get-array.php?oper=getAccounts&all=0&account_types=1,2,1000,2000 retorna:
array (
  'oper' => 'getAccounts',
  'all' => '0',
  'account_types' => '1,2,1000,2000',
)

**Comment by victorcillo** [comment]
i try-get-array.php?oper=getAccounts&all=0&account_types=1|2|1000|2000 retorna:
 array (
  'oper' => 'getAccounts',
  'all' => '0',
  'account_types' => '1|2|1000|2000',
)

**Comment by victorcillo** [comment]
> 1. /php/ctrl/Account.php?oper=getAccounts&all=0&account_types=1,2,1000,2000

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<accounts>
<row id="-1">
<id f="id">
<![CDATA[ -1 ]]>
</id>
<name f="name">
<![CDATA[ Manteniment ]]>
</name>
</row>
<row id="-2">
<id f="id">
<![CDATA[ -2 ]]>
</id>
<name f="name">
<![CDATA[ Consum (stock adjustments) ]]>
</name>
</row>
<row id="-3">
<id f="id">
<![CDATA[ -3 ]]>
</id>
<name f="name">
<![CDATA[ Cashbox ]]>
</name>
</row>
<row id="1001">
<id f="id">
<![CDATA[ 1001 ]]>
</id>
<name f="name">
<![CDATA[ 1 Cistella01 ]]>
</name>
</row>
<row id="1002">
<id f="id">
<![CDATA[ 1002 ]]>
</id>
<name f="name">
<![CDATA[ 2 Cistella02 ]]>
</name>
</row>
<row id="1003">
<id f="id">
<![CDATA[ 1003 ]]>
</id>
<name f="name">
<![CDATA[ 3 Cistella03 ]]>
</name>
</row>
<row id="1004">
<id f="id">
<![CDATA[ 1004 ]]>
</id>
<name f="name">
<![CDATA[ 4 Cistella04 ]]>
</name>
</row>
<row id="1005">
<id f="id">
<![CDATA[ 1005 ]]>
</id>
<name f="name">
<![CDATA[ 5 Cistella05 ]]>
</name>
</row>
<row id="1006">
<id f="id">
<![CDATA[ 1006 ]]>
</id>
<name f="name">
<![CDATA[ 6 Cistella06 ]]>
</name>
</row>
<row id="1007">
<id f="id">
<![CDATA[ 1007 ]]>
</id>
<name f="name">
<![CDATA[ 7 Cistella07 ]]>
</name>
</row>
<row id="1008">
<id f="id">
<![CDATA[ 1008 ]]>
</id>
<name f="name">
<![CDATA[ 8 Cistella08 ]]>
</name>
</row>
<row id="1009">
<id f="id">
<![CDATA[ 1009 ]]>
</id>
<name f="name">
<![CDATA[ 9 Cistella09 ]]>
</name>
</row>
<row id="1010">
<id f="id">
<![CDATA[ 1010 ]]>
</id>
<name f="name">
<![CDATA[ 10 Cistella10 ]]>
</name>
</row>
<row id="1011">
<id f="id">
<![CDATA[ 1011 ]]>
</id>
<name f="name">
<![CDATA[ 11 Cistella11 ]]>
</name>
</row>
<row id="1012">
<id f="id">
<![CDATA[ 1012 ]]>
</id>
<name f="name">
<![CDATA[ 12 Cistella12 ]]>
</name>
</row>
<row id="1013">
<id f="id">
<![CDATA[ 1013 ]]>
</id>
<name f="name">
<![CDATA[ 13 Cistella13 ]]>
</name>
</row>
<row id="1014">
<id f="id">
<![CDATA[ 1014 ]]>
</id>
<name f="name">
<![CDATA[ 14 Cistella14 ]]>
</name>
</row>
<row id="1015">
<id f="id">
<![CDATA[ 1015 ]]>
</id>
<name f="name">
<![CDATA[ 15 Cistella15 ]]>
</name>
</row>
<row id="1016">
<id f="id">
<![CDATA[ 1016 ]]>
</id>
<name f="name">
<![CDATA[ 16 Cistella16 ]]>
</name>
</row>
<row id="1017">
<id f="id">
<![CDATA[ 1017 ]]>
</id>
<name f="name">
<![CDATA[ 17 Cistella17 ]]>
</name>
</row>
<row id="1018">
<id f="id">
<![CDATA[ 1018 ]]>
</id>
<name f="name">
<![CDATA[ 18 Cistella18 ]]>
</name>
</row>
<row id="1019">
<id f="id">
<![CDATA[ 1019 ]]>
</id>
<name f="name">
<![CDATA[ 19 Cistella19 ]]>
</name>
</row>
<row id="1020">
<id f="id">
<![CDATA[ 1020 ]]>
</id>
<name f="name">
<![CDATA[ 20 Cistella20 ]]>
</name>
</row>
<row id="1021">
<id f="id">
<![CDATA[ 1021 ]]>
</id>
<name f="name">
<![CDATA[ 21 Cistella21 ]]>
</name>
</row>
<row id="1022">
<id f="id">
<![CDATA[ 1022 ]]>
</id>
<name f="name">
<![CDATA[ 22 Cistella22 ]]>
</name>
</row>
<row id="1023">
<id f="id">
<![CDATA[ 1023 ]]>
</id>
<name f="name">
<![CDATA[ 23 Cistella23 ]]>
</name>
</row>
<row id="1024">
<id f="id">
<![CDATA[ 1024 ]]>
</id>
<name f="name">
<![CDATA[ 24 Cistella24 ]]>
</name>
</row>
<row id="1025">
<id f="id">
<![CDATA[ 1025 ]]>
</id>
<name f="name">
<![CDATA[ 25 Cistella25 ]]>
</name>
</row>
<row id="1026">
<id f="id">
<![CDATA[ 1026 ]]>
</id>
<name f="name">
<![CDATA[ 26 Cistella26 ]]>
</name>
</row>
<row id="1028">
<id f="id">
<![CDATA[ 1028 ]]>
</id>
<name f="name">
<![CDATA[ 28 Cistella28 ]]>
</name>
</row>
<row id="2009">
<id f="id">
<![CDATA[ 2009 ]]>
</id>
<name f="name">
<![CDATA[ 1009 Ana Mañas ]]>
</name>
</row>
</accounts>

**Comment by victorcillo** [comment]
> 2\. /php/ctrl/Account.php?oper=getAccounts&all=0&account_types=1000

NOTA: No he pogut fer servir la master perque tenim canvis personalitzats per la nostra cooperativa ..

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<accounts>
<row id="1001">
<id f="id">
<![CDATA[ 1001 ]]>
</id>
<name f="name">
<![CDATA[ 1 Cistella01 ]]>
</name>
</row>
<row id="1002">
<id f="id">
<![CDATA[ 1002 ]]>
</id>
<name f="name">
<![CDATA[ 2 Cistella02 ]]>
</name>
</row>
<row id="1003">
<id f="id">
<![CDATA[ 1003 ]]>
</id>
<name f="name">
<![CDATA[ 3 Cistella03 ]]>
</name>
</row>
<row id="1004">
<id f="id">
<![CDATA[ 1004 ]]>
</id>
<name f="name">
<![CDATA[ 4 Cistella04 ]]>
</name>
</row>
<row id="1005">
<id f="id">
<![CDATA[ 1005 ]]>
</id>
<name f="name">
<![CDATA[ 5 Cistella05 ]]>
</name>
</row>
<row id="1006">
<id f="id">
<![CDATA[ 1006 ]]>
</id>
<name f="name">
<![CDATA[ 6 Cistella06 ]]>
</name>
</row>
<row id="1007">
<id f="id">
<![CDATA[ 1007 ]]>
</id>
<name f="name">
<![CDATA[ 7 Cistella07 ]]>
</name>
</row>
<row id="1008">
<id f="id">
<![CDATA[ 1008 ]]>
</id>
<name f="name">
<![CDATA[ 8 Cistella08 ]]>
</name>
</row>
<row id="1009">
<id f="id">
<![CDATA[ 1009 ]]>
</id>
<name f="name">
<![CDATA[ 9 Cistella09 ]]>
</name>
</row>
<row id="1010">
<id f="id">
<![CDATA[ 1010 ]]>
</id>
<name f="name">
<![CDATA[ 10 Cistella10 ]]>
</name>
</row>
<row id="1011">
<id f="id">
<![CDATA[ 1011 ]]>
</id>
<name f="name">
<![CDATA[ 11 Cistella11 ]]>
</name>
</row>
<row id="1012">
<id f="id">
<![CDATA[ 1012 ]]>
</id>
<name f="name">
<![CDATA[ 12 Cistella12 ]]>
</name>
</row>
<row id="1013">
<id f="id">
<![CDATA[ 1013 ]]>
</id>
<name f="name">
<![CDATA[ 13 Cistella13 ]]>
</name>
</row>
<row id="1014">
<id f="id">
<![CDATA[ 1014 ]]>
</id>
<name f="name">
<![CDATA[ 14 Cistella14 ]]>
</name>
</row>
<row id="1015">
<id f="id">
<![CDATA[ 1015 ]]>
</id>
<name f="name">
<![CDATA[ 15 Cistella15 ]]>
</name>
</row>
<row id="1016">
<id f="id">
<![CDATA[ 1016 ]]>
</id>
<name f="name">
<![CDATA[ 16 Cistella16 ]]>
</name>
</row>
<row id="1017">
<id f="id">
<![CDATA[ 1017 ]]>
</id>
<name f="name">
<![CDATA[ 17 Cistella17 ]]>
</name>
</row>
<row id="1018">
<id f="id">
<![CDATA[ 1018 ]]>
</id>
<name f="name">
<![CDATA[ 18 Cistella18 ]]>
</name>
</row>
<row id="1019">
<id f="id">
<![CDATA[ 1019 ]]>
</id>
<name f="name">
<![CDATA[ 19 Cistella19 ]]>
</name>
</row>
<row id="1020">
<id f="id">
<![CDATA[ 1020 ]]>
</id>
<name f="name">
<![CDATA[ 20 Cistella20 ]]>
</name>
</row>
<row id="1021">
<id f="id">
<![CDATA[ 1021 ]]>
</id>
<name f="name">
<![CDATA[ 21 Cistella21 ]]>
</name>
</row>
<row id="1022">
<id f="id">
<![CDATA[ 1022 ]]>
</id>
<name f="name">
<![CDATA[ 22 Cistella22 ]]>
</name>
</row>
<row id="1023">
<id f="id">
<![CDATA[ 1023 ]]>
</id>
<name f="name">
<![CDATA[ 23 Cistella23 ]]>
</name>
</row>
<row id="1024">
<id f="id">
<![CDATA[ 1024 ]]>
</id>
<name f="name">
<![CDATA[ 24 Cistella24 ]]>
</name>
</row>
<row id="1025">
<id f="id">
<![CDATA[ 1025 ]]>
</id>
<name f="name">
<![CDATA[ 25 Cistella25 ]]>
</name>
</row>
<row id="1026">
<id f="id">
<![CDATA[ 1026 ]]>
</id>
<name f="name">
<![CDATA[ 26 Cistella26 ]]>
</name>
</row>
<row id="1028">
<id f="id">
<![CDATA[ 1028 ]]>
</id>
<name f="name">
<![CDATA[ 28 Cistella28 ]]>
</name>
</row>
<row id="2009">
<id f="id">
<![CDATA[ 2009 ]]>
</id>
<name f="name">
<![CDATA[ 1009 Ana Mañas ]]>
</name>
</row>
</accounts>

**Comment by victorcillo** [comment]
> * public function get_accounts_XML($all, $account_types) {

he optat per agafar aquesta opció i funciona conrrectament.

**Comment by jorix** [comment]
> perdona la tardança, he estat molt liat... el try-get-array.php?oper=getAccounts&all=0&account_types=1,2,1000,2000 retorna: array ( 'oper' => 'getAccounts', 'all' => '0', 'account_types' => '1,2,1000,2000', )

És **el què hauria de ser**, així que per aquí res...

> > * public function get_accounts_XML($all, $account_types) {
> 
> he optat per agafar aquesta opció i funciona conrrectament.

Ok

> **NOTA: No he pogut fer servir la master perque tenim canvis personalitzats per la nostra cooperativa ..**

Seria interesant que la vostra personalització la tinguesiu com una bifurcació de master, fins i tot per vosaltres.  
Així ho faig amb la [Cistella-master](https://github.com/jorix/Aixada) 

Es pot veure el codi?  
(Al teu compte els repositoris Aixada estan buits)

**Comment by victorcillo** [comment]
En breus pujaré la nostra versió i crearé la bifurcació.

**Comment by jorix** [comment]
> **NOTA: No he pogut fer servir la master perque tenim canvis personalitzats per la nostra cooperativa ..**
> 
> > 1. /php/ctrl/Account.php?oper=getAccounts&all=0&account_types=1,2,1000,2000
> 
> resposta1.txt archiu adjunt [resposta1.txt](https://github.com/jmueller17/Aixada/files/8147622/resposta1.txt)

Je je, ja he reproduït el problema (99% de probabilitats)

Quan vareu aplicar els canvis del PR #290 segurament ho vareu fer a ma, i potser la cosa va quedar:

```PHP
public function get_accounts_XML($all=0, $account_types) {
    $filter = $this->get_account_types_filter($account_types='');
    // start XML
    $strXML = '';
...
```

en lloc de:

```PHP
public function get_accounts_XML($all=0, $account_types='') {
    $filter = $this->get_account_types_filter($account_types);
    // start XML
    $strXML = '';
...
```

I de fet tu cites:

> @jorix Xavi, acabo de fer un petit canvi,... que fallaven... $filter = $this->get_account_types_filter(**$account_types=''**); ...

Vaig pensar que era un error d'escriptura en el comentari, devia ser un error d'escriptura en el codi.

- - - -

Cap problema, la qüestió era saber el per què, i no tenir un dimoniet no detectable que es pogués manifestar en producció.
