### ISSUE TITLE
Possible bug al validar comandes buides

### ISSUE THREAD

**Issue by mamuts** [jmueller17/Aixada#303]
Bones,
Ens passa sovint que per casualitats una uf ha demanat un sol producte que no ha arribat. Al mirar de validar la comanda apareix buida i el boto de validar està deshabilitat. Això fa que aquesta comada quedi sense validar i apareix indefinidament en el llistat de comandes pendents de validar. La única manera que he trobat és o validar-la manualment a través de phpmyadmin o afegint un producte a la comanda en concret, a través de cerca de productes, i després eliminar el producte fent que el boto de validar es mantingui actiu.

A nivell de codi he estat remanant però no he trobat la manera. El més concret que he trobat és a js/jquery.aixadacart.js, a la línia 138 apareix:
`//if we save, then activate the button right away; for validate we have empty cart, button stays deactivated
  									var keep_disabled = ($this.data('aixadacart').btnType == 'validate')? true:false;
  										$('#btn_submit').button({
							    				label: btn_label,
							    				disabled: keep_disabled});`

Però tot i modificar els paràmetres no hi ha manera. Alguna idea de com fer que el boto de validar estigui actiu encara que la comanda estigui buida?

Gràcies!

**Comment by jorix** [comment]
Efectivament! He pogut reproduir el problema. 

Ho miraré...

- - -

Però una pregunta: **us cal validar UF a UF?**
En el nostre cas la revisió ja suposava que totes les UF es validarien. Així que vaig proposar un *PR* per activar-ho, ara està a *master*
Heu provat doncs de posar a ```config.php``` 
- ```$order_distribution_method = 'choice'``` 
- o el més rotunt ```$order_distribution_method = 'distribute_and_validate' ```

NOTA: Per aquesta via actualment les comandes vuïdes **també queden pendents de validar**. 

AUTO-NOTA: Un cop distribuïda la comanda revisar ```SELECT * FROM  lacistella2.aixada_cart where operator_id is null``` que no tenen registres amb el ```cart_id``` a la taula ```aixada_shop_item```...

**Comment by jorix** [comment]
Prova el PR #305

**Comment by jorix** [comment]
> Bones, Ho he provat i funciona perfectament. Moltes gràcies! No es podrien implementar els canvis que proposes a la branca master? Salut!

Jo no puc, segur que ja ho farà en @jmueller17 

- - -

Per cert mira [laCistella-master](https://github.com/jorix/Aixada/tree/laCistella-master):

*  En el seu moment vaig fer algunes adaptacions per la meva coope i vaig buscar com compatibilitzar-ho sense barrejar-ho amb master d'Aixada. S'usa la carpeta `local_custom`.  ( Els arxiu de `/local_config/lang/` tenen una línia final addicional, `index.php` algunes línies afegides i res més)
* Avui l'he actualitzada amb la *master*. 
* Nosaltres també vam afegir una taula pels torns... 
* Sobre tot vam treballar per tenir uns informes de comandes, útils fer el repartiment, es criden des de `local_custom/order_send.php`.
