### ISSUE TITLE
Error al validar comanda: "generated error 1104:The SELECT would examine more than MAX_JOIN_SIZE rows......status "parsererror" occurred during loading data:Error: Invalid XML:  Warning: Header may not contain more than a single header, new line detected in  ... /php/ctrl/Orders.php on line 163"

### ISSUE THREAD

**Issue by VictorJavaSpring** [jmueller17/Aixada#307]
Hola!, ens ha donat error a l'hora de validar les comandes:
![error_Agost_2023-2gitr](https://github.com/jmueller17/Aixada/assets/13764287/4587d39f-a237-4645-bd87-eabe308b91d9)
...
![error_Agost_2023](https://github.com/jmueller17/Aixada/assets/13764287/e6b91221-acef-4551-aad7-dda8016ceb8f)
... l'error sembla que és a una query, (encara que sembla que també es queixa de que sobra un "header"). L'error surt en un POP UP i després es queda bloquejat .. ![error_loading](https://github.com/jmueller17/Aixada/assets/13764287/299577e3-2559-4fd6-b891-98f6a38c6eae)
 el Pop up mostra el següent texte:
```
An error "Error: Invalid XML: 
Warning: Header may not contain more than a single header, 
new line detected in 
/customers/2/d/4/girasoldesantmarti.net/httpd.www/aixada/php/ctrl/Orders.php on line 163

        SELECT id, name, unit,
            max(r.uf_price) uf_price,
            max(r.rev_tax_percent) rev_tax_percent,
            max(r.iva_percent) iva_percent,
            round( max(r.uf_price) / 
                (1 + max(r.rev_tax_percent)/100) /
                (1 + max(r.iva_percent)/100), 2 ) gross_price,
            round( max(r.uf_price) / 
                (1 + max(r.rev_tax_percent)/100), 2 ) net_price
        FROM(
        select distinct
            p.id, p.name,
            if(p.orderable_type_id=3, 
                '(comentarios pedido)',
                um.unit) unit,
            ifnull(ots.unit_price_stamp, oi.unit_price_stamp) uf_price,
            ifnull(ots.rev_tax_percent, rev.rev_tax_percent) rev_tax_percent,
            ifnull(ots.iva_percent, iva.percent) iva_percent            
        from
            aixada_order_item oi
        left join 
            aixada_order_to_shop ots
        on  oi.id = ots.order_item_id
        join (
            aixada_product p,
            aixada_rev_tax_type rev, 
            aixada_iva_type iva,
            aixada_unit_measure um
        ) on 
            oi.product_id = p.id
            and rev.id = p.rev_tax_type_id
            and iva.id = p.iva_percent_id
            and um.id =  p.unit_measure_order_id where oi.order_id = 1556) r
        group by id, name, unit
        order by name; 
		generated error 1104: 
		The SELECT would examine more than MAX_JOIN_SIZE rows; 
		check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# 
		if the SELECT is okay", 
		status "parsererror" occurred during loading data: 
Warning:Header may not contain more than a single header, new line detected in 
/customers/2/d/4/girasoldesantmarti.net/httpd.www/aixada/php/ctrl/Orders.php 
on line 163

        SELECT id, name, unit,
            max(r.uf_price) uf_price,
            max(r.rev_tax_percent) rev_tax_percent,
            max(r.iva_percent) iva_percent,
            round( max(r.uf_price) / 
                (1 + max(r.rev_tax_percent)/100) /
                (1 + max(r.iva_percent)/100), 2 ) gross_price,
            round( max(r.uf_price) / 
                (1 + max(r.rev_tax_percent)/100), 2 ) net_price
        FROM(
        select distinct
            p.id, p.name,
            if(p.orderable_type_id=3, 
                '(comentarios pedido)',
                um.unit) unit,
            ifnull(ots.unit_price_stamp, oi.unit_price_stamp) uf_price,
            ifnull(ots.rev_tax_percent, rev.rev_tax_percent) rev_tax_percent,
            ifnull(ots.iva_percent, iva.percent) iva_percent            
        from
            aixada_order_item oi
        left join 
            aixada_order_to_shop ots
        on  oi.id = ots.order_item_id
        join (
            aixada_product p,
            aixada_rev_tax_type rev, 
            aixada_iva_type iva,
            aixada_unit_measure um
        ) on 
            oi.product_id = p.id
            and rev.id = p.rev_tax_type_id
            and iva.id = p.iva_percent_id
            and um.id =  p.unit_measure_order_id where oi.order_id = 1556) r
        group by id, name, unit
        order by name; 
generated error 1104: 
The SELECT would examine more than MAX_JOIN_SIZE rows;
check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay
```
He estat mirant i crec que on falla és al case 'getOrdersListing' de l'arxiu /php/control/Orders.php a:
```
    switch (get_param('oper')) {

    	//returns a list of all orders summarized by provider within a given date range
    	case 'getOrdersListing':
    		echo get_orders_in_range(get_param('filter'), get_param('uf_id',0), get_param('fromDate',0), get_param('toDate',0), 
                get_param('steps',0), get_param('range',0));
    		exit; 

```
La URL que monta és :
http://www.girasoldesantmarti.net/aixada/manage_orders.php?filter=ordersForToday&lastPage=torn.php

Adjunto imatges, si teniu alguna idea, ens farieu un favor perqué no podem validar!

**Comment by VictorJavaSpring** [comment]
Nota: Lo dels headers crec que es refereix a les línies finals del Orders.php :
```
catch(Exception $e) {
    header('HTTP/1.0 401 ' . $e->getMessage());
    die ($e->getMessage());
}  
```

**Comment by VictorJavaSpring** [comment]
He trobat aquesta info:
_This error can occur if the MySQL query optimizer determines that the number of examined rows is going to exceed MAX_JOIN_SIZE. Setting the MySQL System Variable SQL_BIG_SELECTS=1 may resolve this error since doing so will cause the value for MAX_JOIN_SIZE to be ignored._
i també aquests links, on donen diverses opcions:
https://stackoverflow.com/questions/950465/mysql-sql-big-selects
https://stackoverflow.com/questions/22630238/error-set-sql-big-selects-1-or-set-max-join-size

**Comment by jorix** [comment]
Ja veig...

Crec que es podria millorar l'eficiència d'aquesta `SELECT` amb afegint una clau primaria a `aixada_order_to_shop`:
```sql
ALTER TABLE aixada_order_to_shop add primary key (order_item_id);
```

**PETICIÓ**:  
  1.- Asegura't que `SQL_BIG_SELECTS=0`
  2.- Prova si falla abans de fer el canvi.
  3.- Afegeix la clau primaria a `aixada_order_to_shop`.
  4.- Prova si funciona un cop fet el canvi.
  5.- Informa dels resultats a aquest mateix issue.

**ATENCIÓ**:  
Abans hauries de mirar que aquesta sentencia:
```sql
select count(*) from (
  SELECT order_item_id, count(*) FROM aixada_order_to_shop os group by order_item_id having count(*) > 1
) g;
```
 retorna un `0`!!

- - -

@jmueller17 : Què opines? 
Si et sembla faria un PR amb un canvi de BD que s'actibaria només si el `select count(*)` retorna `0`.  
Tot això un cop @VictorJavaSpring confirmés que no apareixen problemes en el dia a dia.

**Comment by jorix** [comment]
> Nota: Lo dels headers crec que es refereix a les línies finals del Orders.php...

No té importancia, es normal que apareigui quan Aixada informa d'un error.

**Comment by VictorJavaSpring** [comment]
select count(*) from (
  SELECT order_item_id, count(*) FROM aixada_order_to_shop os group by order_item_id having count(*) > 1
) g; retorna **34** !

ALTER TABLE aixada_order_to_shop add primary key (order_item_id) retorna un #1062 - Duplicate entry '386685' for key 'PRIMARY'
SELECT * FROM `aixada_order_to_shop` WHERE ORDER_ITEM_ID = 386685; retorna 1 registre només..

**Comment by jorix** [comment]
> ... retorna **34** !
 
Bé doncs fes:
```sql
ALTER TABLE aixada_order_to_shop add index (order_item_id);
```

Amb això la BD de dades ja tindrà un index per optimitzar la `SELECT`, i suposo que ja no es produirà l'error `The SELECT would examine more than MAX_JOIN_SIZE rows;`
 - - -

Però...  
m'intriga com es creen aquests duplicats.  
Sense poder bussejar a la BD m'hes dificil d'imaginar...

**Comment by VictorJavaSpring** [comment]
Provant el canvi...

**Comment by VictorJavaSpring** [comment]
Els canvis han desbloquejat l'error de moment, gràcies.
